version: "3.8"
services:
  backend:
    container_name: backend-server
    image: fixfireza/noteams-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
